# Generated by Django 4.2.1 on 2023-05-31 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tutor", "0002_alter_course_description_alter_course_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_tutor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
