# Generated by Django 4.2.1 on 2023-06-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
